name: Build and Release

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-csharp:
    name: Build C# Projects
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - week6/csharp/adapter_pattern/AdapterPatternApp/AdapterPatternApp.csproj
          - week6/csharp/decorator_pattern/DecoratorPatternApp/DecoratorPatternApp.csproj
          - week6/csharp/facade_pattern/FacadePatternApp/FacadePatternApp.csproj
          - week6/csharp/factory_method_pattern/FactoryMethodPatternApp/FactoryMethodPatternApp.csproj
          - week6/csharp/method_chaining_pattern/MethodChainingPatternApp/MethodChainingPatternApp.csproj
          - week6/csharp/method_chaining_pattern/builder_pattern/BuilderPatternApp/BuilderPatternApp.csproj

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build C# Project
        run: |
          dotnet build ${{ matrix.project }} --configuration Release
          project_dir=$(dirname ${{ matrix.project }})
          mkdir -p build_outputs/csharp/$(basename $project_dir)
          cp -r $project_dir/bin/Release/* build_outputs/csharp/$(basename $project_dir)/

      - name: Upload C# Build Outputs
        uses: actions/upload-artifact@v3
        with:
          name: csharp-build-outputs
          path: build_outputs/csharp

  build-cpp:
    name: Build C++ Projects
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - week6/cpp/adapter_pattern
          - week6/cpp/decorator_pattern
          - week6/cpp/facade_pattern
          - week6/cpp/factory_method_pattern
          - week6/cpp/method_chaining_pattern
          - week6/cpp/method_chaining_pattern/builder_pattern

    steps:
      - uses: actions/checkout@v3

      - name: Install g++
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Compile C++ Project
        run: |
          mkdir -p build_outputs/cpp/$(basename ${{ matrix.project }})
          g++ ${{ matrix.project }}/*.cpp -o build_outputs/cpp/$(basename ${{ matrix.project }})/app

      - name: Upload C++ Build Outputs
        uses: actions/upload-artifact@v3
        with:
          name: cpp-build-outputs
          path: build_outputs/cpp

  build-kotlin:
    name: Build Kotlin Projects
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - week6/kotlin/adapter_pattern/Adapter.kt
          - week6/kotlin/decorator_pattern/Coffee.kt
          - week6/kotlin/facade_pattern/Computer.kt
          - week6/kotlin/factory_method_pattern/Animal.kt
          - week6/kotlin/method_chaining_pattern/Calculator.kt
          - week6/kotlin/method_chaining_pattern/builder_pattern/Person.kt

    steps:
      - uses: actions/checkout@v3

      - name: Set up Kotlin Compiler
        run: sudo apt-get update && sudo apt-get install -y kotlin

      - name: Compile Kotlin File to JAR
        run: |
          kt_file=${{ matrix.project }}
          output_dir=build_outputs/kotlin/$(basename $(dirname $kt_file))
          mkdir -p $output_dir
          kotlinc $kt_file -include-runtime -d $output_dir/$(basename $kt_file .kt).jar

      - name: Upload Kotlin Build Outputs
        uses: actions/upload-artifact@v3
        with:
          name: kotlin-build-outputs
          path: build_outputs/kotlin

  release:
    name: Create GitHub Release
    needs: [build-csharp, build-cpp, build-kotlin]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - uses: actions/checkout@v3

      - name: Download C# Build Outputs
        uses: actions/download-artifact@v3
        with:
          name: csharp-build-outputs
          path: build_outputs/csharp

      - name: Download C++ Build Outputs
        uses: actions/download-artifact@v3
        with:
          name: cpp-build-outputs
          path: build_outputs/cpp

      - name: Download Kotlin Build Outputs
        uses: actions/download-artifact@v3
        with:
          name: kotlin-build-outputs
          path: build_outputs/kotlin

      - name: Archive build outputs
        run: zip -r release-artifacts.zip build_outputs

      - name: Upload GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release-artifacts.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
